DROP TABLE IF EXISTS prompts;
DROP TABLE IF EXISTS student;

CREATE TABLE student (
  StudentID INTEGER PRIMARY KEY AUTOINCREMENT,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  StudentName TEXT NOT NULL,
  StudentEmail TEXT NOT NULL
);

CREATE TABLE prompts (
  PromptID INTEGER PRIMARY KEY AUTOINCREMENT,
  StudentID int,
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Style TEXT NOT NULL,
  Reference TEXT NOT NULL,
  Msg TEXT NOT NULL,
  FOREIGN KEY (StudentID) REFERENCES student(StudentID)
);